<a href="https://colab.research.google.com/github/JCMVP92/-Delincuencia-Mexico-/blob/main/Delincuencia_en_Mexico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importar librerias 
#Visualisation libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import datetime
import math
import matplotlib.mlab as mlab
import matplotlib

In [ ]:
#Importamos la DATA desde el PC
delincuencia = pd.read_excel("IDEFC_NM_ago22.xlsx")
delincuencia.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total de delitos
0,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,18.0
1,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
2,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0.0,0.0,2.0,2.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,12.0
3,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
#obtenemos la informacion de la DATA para saber que tipos de datos tenemos
delincuencia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25088 entries, 0 to 25087
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     25088 non-null  float64
 1   Clave_Ent               25088 non-null  float64
 2   Entidad                 25088 non-null  object
 3   Bien jurídico afectado  25088 non-null  object
 4   Tipo de delito          25088 non-null  object
 5   Subtipo de delito       25088 non-null  object
 6   Modalidad               25088 non-null  object
 7   Enero                   25088 non-null  float64
 8   Febrero                 25088 non-null  float64
 9   Marzo                   25088 non-null  float64
 10  Abril                   25088 non-null  float64
 11  Mayo                    25088 non-null  float64
 12  Junio                   25088 non-null  float64
 13  Julio                   25088 non-null  float64
 14  Agosto                  25088 non-null  float64
 15  Septiembre              21952 non-null  float64
 16  Octubre                 21952 non-null  float64
 17  Noviembre               21952 non-null  float64
 18  Diciembre               21952 non-null  float64
 19  Total de delitos        21952 non-null  float64
dtypes: float64(15), object(5)
memory usage: 3.8+ MB

In [ ]:
#revisamos el numero de columnas y filas que tiene la data
delincuencia.shape

(25088, 20)

In [ ]:
#Eliminamos los NA del Data
delincuencia = delincuencia.fillna(0)
delincuencia

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total de delitos
0,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3.0,0.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,18.0
1,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,5.0
2,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0.0,0.0,2.0,2.0,3.0,2.0,0.0,1.0,2.0,0.0,0.0,0.0,12.0
3,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
4,2015.0,1.0,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25083,2022.0,32.0,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Falsificación,Falsificación,Falsificación,5.0,14.0,7.0,10.0,9.0,19.0,6.0,5.0,0.0,0.0,0.0,0.0,0.0
25084,2022.0,32.0,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Contra el medio ambiente,Contra el medio ambiente,Contra el medio ambiente,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25085,2022.0,32.0,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,12.0,26.0,45.0,84.0,26.0,26.0,22.0,31.0,0.0,0.0,0.0,0.0,0.0
25086,2022.0,32.0,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,1.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25087,2022.0,32.0,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,146.0,122.0,174.0,150.0,134.0,170.0,139.0,183.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Revisamos que no tengamos ningun NA
delincuencia.isna().sum()

Año                       0
Clave_Ent                 0
Entidad                   0
Bien jurídico afectado    0
Tipo de delito            0
Subtipo de delito         0
Modalidad                 0
Enero                     0
Febrero                   0
Marzo                     0
Abril                     0
Mayo                      0
Junio                     0
Julio                     0
Agosto                    0
Septiembre                0
Octubre                   0
Noviembre                 0
Diciembre                 0
Total de delitos          0
dtype: int64

In [ ]:
#Convertimos los datos de Float a Int que para nuestro estudio los decimales no son validos
delincuencia[["Año","Clave_Ent","Enero","Febrero","Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto","Septiembre","Octubre","Noviembre","Diciembre", "Total de delitos"]] = delincuencia[["Año","Clave_Ent","Enero","Febrero","Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto","Septiembre","Octubre","Noviembre","Diciembre", "Total de delitos"]].astype(int) 
print(delincuencia.dtypes)

Año                        int64
Clave_Ent                  int64
Entidad                   object
Bien jurídico afectado    object
Tipo de delito            object
Subtipo de delito         object
Modalidad                 object
Enero                      int64
Febrero                    int64
Marzo                      int64
Abril                      int64
Mayo                       int64
Junio                      int64
Julio                      int64
Agosto                     int64
Septiembre                 int64
Octubre                    int64
Noviembre                  int64
Diciembre                  int64
Total de delitos           int64
dtype: object

In [ ]:
#damos formato a la Columna de Año como date
delincuencia['Año'] = delincuencia['Año'].apply(pd.to_datetime,format='%Y')

In [ ]:
delincuencia.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25088 entries, 1970 to 1970
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Clave_Ent               25088 non-null  int64
 1   Entidad                 25088 non-null  object
 2   Bien jurídico afectado  25088 non-null  object
 3   Tipo de delito          25088 non-null  object
 4   Subtipo de delito       25088 non-null  object
 5   Modalidad               25088 non-null  object
 6   Enero                   25088 non-null  int64
 7   Febrero                 25088 non-null  int64
 8   Marzo                   25088 non-null  int64
 9   Abril                   25088 non-null  int64
 10  Mayo                    25088 non-null  int64
 11  Junio                   25088 non-null  int64
 12  Julio                   25088 non-null  int64
 13  Agosto                  25088 non-null  int64
 14  Septiembre              25088 non-null  int64
 15  Octubre                 25088 non-null  int64
 16  Noviembre               25088 non-null  int64
 17  Diciembre               25088 non-null  int64
dtypes: int64(13), object(5)
memory usage: 3.6+ MB

In [ ]:
delincuencia.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre,Total de delitos
0,2015-01-01,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2,1,2,2,2,1,18
1,2015-01-01,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0,1,0,0,0,1,5
2,2015-01-01,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0,1,2,0,0,0,12
3,2015-01-01,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0,0,0,0,0,0,3
4,2015-01-01,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0,0,0,0,0,0,1

In [ ]:
#creamos un grouoby
delincuencia.groupby(['Entidad', 'Tipo de delito',"Modalidad"]).size()

Entidad         Tipo de delito                                                                 Modalidad
Aguascalientes  Aborto                                                                         Aborto                                                                           8
                Abuso de confianza                                                             Abuso de confianza                                                               8
                Abuso sexual                                                                   Abuso sexual                                                                     8
                Acoso sexual                                                                   Acoso sexual                                                                     8
                Allanamiento de morada                                                         Allanamiento de morada                                                           8
                                                                                                                                                                               ..
Zacatecas       Tráfico de menores                                                             Tráfico de menores                                                               8
                Violación equiparada                                                           Violación equiparada                                                             8
                Violación simple                                                               Violación simple                                                                 8
                Violencia de género en todas sus modalidades distinta a la violencia familiar  Violencia de género en todas sus modalidades distinta a la violencia familiar    8
                Violencia familiar                                                             Violencia familiar                                                               8
Length: 2176, dtype: int64

In [ ]:
pt = pd.pivot_table(delincuencia,index=["Año","Entidad", "Tipo de delito"],values=["Total de delitos"],aggfunc=[np.mean,len])
pt

                                                                                         mean  \
                                                                             Total de delitos
Año        Entidad        Tipo de delito
2015-01-01 Aguascalientes Aborto                                                          5.0
                          Abuso de confianza                                            419.0
                          Abuso sexual                                                   18.0
                          Acoso sexual                                                    0.0
                          Allanamiento de morada                                        169.0
...                                                                                       ...
2022-01-01 Zacatecas      Tráfico de menores                                              0.0
                          Violación equiparada                                            0.0
                          Violación simple                                                0.0
                          Violencia de género en todas sus modalidades di...              0.0
                          Violencia familiar                                              0.0

                                                                                          len
                                                                             Total de delitos
Año        Entidad        Tipo de delito
2015-01-01 Aguascalientes Aborto                                                            1
                          Abuso de confianza                                                1
                          Abuso sexual                                                      1
                          Acoso sexual                                                      1
                          Allanamiento de morada                                            1
...                                                                                       ...
2022-01-01 Zacatecas      Tráfico de menores                                                1
                          Violación equiparada                                              1
                          Violación simple                                                  1
                          Violencia de género en todas sus modalidades di...                1
                          Violencia familiar                                                1

[10240 rows x 2 columns]

In [ ]:
delincuencia[["Entidad","Modalidad","Total de delitos"]].value_counts()

Entidad    Modalidad           Total de delitos
Yucatán    Con violencia       0                   85
Colima     Con violencia       0                   64
Tabasco    Con violencia       0                   61
Campeche   Sin violencia       0                   59
Nayarit    Sin violencia       0                   58
                                                   ..
Hidalgo    Con arma de fuego   4                    1
                               5                    1
                               6                    1
                               8                    1
Zacatecas  Violencia familiar  3453                 1
Length: 16089, dtype: int64

In [ ]:
pd.pivot_table(delincuencia,index=["Año","Entidad","Tipo de delito"],values=["Diciembre", "Enero"],aggfunc=np.sum)

                                                                              Diciembre  \
Año        Entidad        Tipo de delito
2015-01-01 Aguascalientes Aborto                                                      0
                          Abuso de confianza                                         26
                          Abuso sexual                                                1
                          Acoso sexual                                                0
                          Allanamiento de morada                                      9
...                                                                                 ...
2022-01-01 Zacatecas      Tráfico de menores                                          0
                          Violación equiparada                                        0
                          Violación simple                                            0
                          Violencia de género en todas sus modalidades di...          0
                          Violencia familiar                                          0

                                                                              Enero
Año        Entidad        Tipo de delito
2015-01-01 Aguascalientes Aborto                                                  0
                          Abuso de confianza                                     41
                          Abuso sexual                                            6
                          Acoso sexual                                            0
                          Allanamiento de morada                                 13
...                                                                             ...
2022-01-01 Zacatecas      Tráfico de menores                                      0
                          Violación equiparada                                    5
                          Violación simple                                        7
                          Violencia de género en todas sus modalidades di...      0
                          Violencia familiar                                    194

[10240 rows x 2 columns]

In [ ]:
delitos_mas_cometidos = delincuencia[delincuencia["Total de delitos" ] != 1].sort_values(by="Entidad", ascending=True)

z= delitos_mas_cometidos[["Entidad", "Tipo de delito", "Modalidad", "Total de delitos"]]

z

,Entidad,Tipo de delito,Modalidad,Total de delitos
0,Aguascalientes,Homicidio,Con arma de fuego,18
9445,Aguascalientes,Incesto,Incesto,0
9444,Aguascalientes,Violación equiparada,Violación equiparada,58
9443,Aguascalientes,Violación simple,Violación simple,175
9442,Aguascalientes,Hostigamiento sexual,Hostigamiento sexual,82
...,...,...,...,...
3040,Zacatecas,Homicidio,Con otro elemento,46
3041,Zacatecas,Homicidio,No especificado,0
3042,Zacatecas,Homicidio,Con arma de fuego,0
6217,Zacatecas,Robo,Robo de motocicleta Con violencia,24
25087,Zacatecas,Otros delitos del Fuero Común,Otros delitos del Fuero Común,0

In [ ]:
s = delincuencia[["Tipo de delito",'Modalidad']].value_counts().to_frame()[:5]
s.style.background_gradient(cmap='Reds')